apiVersion: apps/v1
kind: Deployment

metadata:
  name: train-ticket-reservation

spec:
  replicas: 2

  selector:
    matchLabels:
      app: train-ticket-reservation

  template:
    metadata:
      labels:
        app: train-ticket-reservation

    spec:
      containers:
      - name: train-ticket-reservation
        image: IMAGE_NAME
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
